### PR TITLE
DOCSP-40749-many-to-one-limitation

### PR DESCRIPTION
**Pull request by jason-price-mongodb**
Add views limitation per JIRA. Kept it minimal to avoid the weeds, which might be subject to many changes.

JIRA:
https://jira.mongodb.org/browse/DOCSP-40749

Build log:
https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6675f7e8ebce19f314fc3fcd

Staging:
https://preview-mongodbjasonpricemongodb.gatsbyjs.io/cluster-sync/DOCSP-40749-many-to-one-limitation/reference/limitations/#multiple-source-sync-limitations

### CODE REVIEW

**Review by sarah-olson-mongodb — COMMENTED** [review]
Thanks @jason-price-mongodb! LGTM with an optional suggestion for your consideration.

What do you think about moving the name space paragraph below the example, so it's located next to views. Then you have the main limitation, the example, and then two additional limitations. I might also consider putting the name space and views limitation in a bulleted list.

**Review by sarah-olson-mongodb — APPROVED** [review]
LGTM!

**Comment by jason-price-mongodb** [comment]
Asked Craven to review through Slack. Cannot add him as a reviewer.

**Review by suspicious-mango — APPROVED** [review]
LGTM.

**Pull request merged**
