### PR TITLE
DOCSP-28129 error response

### PR DESCRIPTION
**Pull request by davemungo**
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/cluster-sync/docsworker-xlarge/DOCSP-28129-progress-endoint-v1.2/reference/api/progress/)

[JIRA](https://jira.mongodb.org/browse/DOCSP-28129)

[build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63efc14b05dd3cc814e65aec)

### CODE REVIEW

**Review by jmd-mongo — APPROVED** [review]
This one LGTM! Thanks for the updates, @davemungo.

**Comment by davemungo** [comment]
@autarch would you have a look at this docs PR when you get a moment?

**Review by autarch — CHANGES_REQUESTED** [review]
This works the same way for all the other endpoints, so I think this should be shown in the same way.

With `/progress`, you _either_ get the various info fields _or_ a document with just the error info. You can't get both, but the way this is formatted makes it look like you can.

**Review by davemungo — COMMENTED** [review]
@autarch  I'm confused, the endpoints are all formatted the same way - all possible responses are listed in a single table. I don't think it makes sense to break all of the endpoints into two tables (error and success) since all of the tables except this one are only 3 lines long. 

Instead, I've changed the wording for the /progress endpoint and added an introductory line to try to highlight the distinction between status and error messages.

**Comment by autarch** [comment]
> @autarch I'm confused, the endpoints are all formatted the same way - all possible responses are listed in a single table. I don't think it makes sense to break all of the endpoints into two tables (error and success) since all of the tables except this one are only 3 lines long.

Doh, _I_ was confused. Now I see you're correct. It's just that the other endpoints don't really have a significant body unless there's an error, so it looks like it's just documenting an error response.

> Instead, I've changed the wording for the /progress endpoint and added an introductory line to try to highlight the distinction between status and error messages.

This is helpful, I think.

Longer-term, I think it's on us to change how this behaves. We should not be returning a 200 status for errors, and we should document the 200 response separately from other statuses.

**Review by davemungo — COMMENTED** [review]
@autarch   Sounds good.  Is this ok to merge in for now?

**Review by autarch — APPROVED** [review]
LGTM!

**Comment by autarch** [comment]
> @autarch Sounds good. Is this ok to merge in for now?

Yes, sorry for the confusion.

**Pull request merged**
