### PR TITLE
Docsp 30395 adding index consistency limitations 

### PR DESCRIPTION
**Pull request by ltran-mdb2**
## DESCRIPTION

adding mongosync limitation about consistent index specifications

## STAGING

https://preview-mongodbltranmdb2.gatsbyjs.io/cluster-sync/DOCSP-30395/reference/limitations/#sharded-clusters

## JIRA

https://jira.mongodb.org/browse/DOCSP-30395

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=651f15a8885de6b26bd335a4

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Is this free of spelling errors?
- [x] Is this free of grammatical errors?
- [x] Is this free of staging / rendering issues?
- [x] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Comment by ltran-mdb2** [comment]
Note that https://jira.mongodb.org/browse/DOCSP-33393 addresses the build log error.

**Review by sarah-olson-mongodb — APPROVED** [review]
Thanks for these updates @ltran-mdb2. LGTM

**Comment by ltran-mdb2** [comment]
HI @ajayvijayakumar123 ! Would you be able to give this a tech review when you get a moment?

**Review by ajayvijayakumar123 — APPROVED** [review]
LGTM!

**Pull request merged**
